spring:
  application:
    name: rabbit-gradle
  cloud:
    stream:
      rabbit:
        bindings:
          output:
            producer:
              bindingRoutingKey: "PARA-FILA-1"
              routingKeyExpression: '''PARA-FILA-1'''
              exchangeType: direct
              bindQueue: true
          input:
            consumer:
              autoBindDlq: true
              group: messageInputSubscriber
              bindingRoutingKey: "PARA-FILA-1"
              bindQueue: true
      bindings:
        output:
          destination: FILA-EMPLOYEE
          producer:
            requiredGroups: DESTINO
        input:
          destination: FILA-EMPLOYEE
          group: DESTINO
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: kamisama123





